name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/electrode-deploy/Electrode
            git pull origin main

            cd ..
            docker compose build backend
            docker compose up -d backend

            docker image prune -f
